### ISSUE TITLE
INDUCCION

### ISSUE THREAD

**Issue by Felix-Angel** [SistemasTecTlaxiaco/actividad-9-practica-de-inducci-n-matem-tica-equipo-mayra-diego-daniel-felix#1]
[INDUCCIÓN MATEMATICA_EQUIPO.pdf](https://github.com/SistemasTecTlaxiaco/actividad-9-practica-de-inducci-n-matem-tica-equipo-mayra-diego-daniel-felix/files/13223313/INDUCCION.MATEMATICA_EQUIPO.pdf)

**Comment by elisa1223** [comment]
Portada: 25%
Procedimiento: 25%
Figuras,ilustraciones y fotografias: 22.5%
Resultados y conclusiones: 25%

Calificación final: 19.5/20
Evaluado por el equipo de Elisa.

**Comment by josealfredo79** [comment]
Bien hecho y revisado...
